import { Planet } from "./types";

export const planetsData: Planet[] = [
  {
    id: "surya",
    name: "सूर्य ग्रह",
    englishName: "Surya - Sun",
    deity: "अग्नि / शिव",
    dhyanMantra: "जपाकुसुम संकाशं काश्यपेयं महाद्युतिम्।\nतमोऽरिं सर्वपापघ्नं प्रणतोऽस्मि दिवाकरम्॥",
    gayatriMantra: "ॐ आदित्याय विद्महे प्रभाकराय धीमहि, तन्नः सूर्यः प्रचोदयात्॥",
    vedoktaMantra: "ॐ आ कृष्णेन रजसा वर्तमानो निवेशयन्नमृतं मर्त्यं च ।\nहिरण्ययेन सविता रथेना देवो याति भुवनानि पश्यन्॥",
    beejMantra: "ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः ॥",
    japCount: "७,००० (कलियुगे ४ गुना: २८,०००)",
    samidha: "मदार (आक)",
    gemstone: "माणिक्य (Ruby)",
    direction: "पूर्व",
    colorTheme: {
      bg: "bg-red-600",
      text: "text-red-700",
      border: "border-red-200",
      lightBg: "bg-red-50",
    },
  },
  {
    id: "chandra",
    name: "चन्द्र ग्रह",
    englishName: "Chandra - Moon",
    deity: "अपः (जल) / गौरी",
    dhyanMantra: "दधिशंखतुषाराभं क्षीरोदार्णव सम्भवम्।\nनमामि शशिनं सोमं शम्भोर्मुकुट भूषणम्॥",
    gayatriMantra: "ॐ क्षीरपुत्राय विद्महे अमृततत्त्वाय धीमहि, तन्नो चन्द्रः प्रचोदयात्॥",
    vedoktaMantra: "ॐ इमं देवा असपत्न सुवध्वं महते क्षत्राय महते ज्यैष्ठ्याय महते जानराज्यायेन्द्रस्येन्द्रियाय ।\nइमममुष्य पुत्रममुष्यै पुत्रमस्यै विश एष वोऽमी राजा सोमोऽस्माकं ब्राह्मणाना राजा ॥",
    beejMantra: "ॐ श्रां श्रीं श्रौं सः चन्द्रमसे नमः ॥",
    japCount: "११,००० (कलियुगे ४४,०००)",
    samidha: "पलाश",
    gemstone: "मोती (Pearl)",
    direction: "वायव्य",
    colorTheme: {
      bg: "bg-slate-300",
      text: "text-slate-700",
      border: "border-slate-200",
      lightBg: "bg-slate-50",
    },
  },
  {
    id: "mangal",
    name: "मङ्गल ग्रह",
    englishName: "Mangal - Mars",
    deity: "पृथ्वी / क्षेत्रपाल (कार्तिकेय)",
    dhyanMantra: "धरणीगर्भ संभूतं विद्युत्कान्ति समप्रभम्।\nकुमारं शक्तिहस्तं च मंगलं प्रणमाम्यहम्॥",
    gayatriMantra: "ॐ अंगारकाय विद्महे शक्तिहस्ताय धीमहि, तन्नो भौमः प्रचोदयात्॥",
    vedoktaMantra: "ॐ अग्निर्मूर्धा दिवः ककुत्पतिः पृथिव्या अयम्।\nअपा रेतांसि जिन्वति ॥",
    beejMantra: "ॐ क्रां क्रीं क्रौं सः भौमाय नमः ॥",
    japCount: "१०,००० (कलियुगे ४०,०००)",
    samidha: "खैर (खदिर)",
    gemstone: "मूँगा (Red Coral)",
    direction: "दक्षिण",
    colorTheme: {
      bg: "bg-rose-700",
      text: "text-rose-800",
      border: "border-rose-200",
      lightBg: "bg-rose-50",
    },
  },
  {
    id: "budh",
    name: "बुध ग्रह",
    englishName: "Budh - Mercury",
    deity: "विष्णु / नारायण",
    dhyanMantra: "प्रियंगुकलिकाश्यामं रूपेणाप्रतिमं बुधम्।\nसौम्यं सौम्यगुणोपेतं तं बुधं प्रणमाम्यहम्॥",
    gayatriMantra: "ॐ सौम्यरूपाय विद्महे वाणेशाय धीमहि, तन्नो सौम्यः प्रचोदयात्॥",
    vedoktaMantra: "ॐ उद्बुध्यस्वाग्ने प्रति जागृहि त्वमिष्टापूर्ते ससृजेथामयं च ।\nअस्मिन्त्सधस्थे अध्युत्तरस्मिन् विश्वे देवा यजमानश्च सीदत ॥",
    beejMantra: "ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः ॥",
    japCount: "९,००० (कलियुगे ३६,०००)",
    samidha: "अपामार्ग (चिचड़ा)",
    gemstone: "पन्ना (Emerald)",
    direction: "उत्तर",
    colorTheme: {
      bg: "bg-emerald-600",
      text: "text-emerald-700",
      border: "border-emerald-200",
      lightBg: "bg-emerald-50",
    },
  },
  {
    id: "brihaspati",
    name: "गुरु / बृहस्पति ग्रह",
    englishName: "Brihaspati - Jupiter",
    deity: "ब्रह्मा / इन्द्र",
    dhyanMantra: "देवानां च ऋषीणां च गुरुं काञ्चनसंनिभम्।\nबुद्धिभूतं त्रिलोकेशं तं नमामि बृहस्पतिम्॥",
    gayatriMantra: "ॐ अंगिरसाय विद्महे दिव्यदेहाय धीमहि, तन्नो जीवः प्रचोदयात्॥",
    vedoktaMantra: "ॐ बृहस्पते अति यदर्यो अर्हाद् द्युमद्विभाति क्रतुमज्जनेषु।\nयद्दीदयच्छवस ऋतप्रजात तदस्मासु द्रविणं धेहि चित्रम्॥",
    beejMantra: "ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः ॥",
    japCount: "१९,००० (कलियुगे ७६,०००)",
    samidha: "पीपल (अश्वत्थ)",
    gemstone: "पुखराज (Yellow Sapphire)",
    direction: "ईशान",
    colorTheme: {
      bg: "bg-amber-500",
      text: "text-amber-700",
      border: "border-amber-200",
      lightBg: "bg-amber-50",
    },
  },
  {
    id: "shukra",
    name: "शुक्र ग्रह",
    englishName: "Shukra - Venus",
    deity: "इन्द्राणी / मरुत्वान",
    dhyanMantra: "हिमकुन्दमृणालाभं दैत्यानां परमं गुरुम्।\nसर्वशास्त्रप्रवक्तारं भार्गवं प्रणमाम्यहम्॥",
    gayatriMantra: "ॐ भृगुसुताय विद्महे दिव्यदेहाय धीमहि, तन्नो शुक्रः प्रचोदयात्॥",
    vedoktaMantra: "ॐ अन्नात्परिस्रुतो रसं ब्रह्मणा व्यपिबत् क्षत्रं पयः सोमं प्रजापतिः ।\nऋतेन सत्यमिन्द्रियं विपान शुक्रमन्धस इन्द्रस्येन्द्रियमिदं पयोऽमृतं मधु॥",
    beejMantra: "ॐ द्रां द्रीं द्रौं सः शुक्राय नमः ॥",
    japCount: "१६,००० (कलियुगे ६४,०००)",
    samidha: "गूलर (उदुम्बर)",
    gemstone: "हीरा (Diamond) / ओपल",
    direction: "आग्नेय",
    colorTheme: {
      bg: "bg-fuchsia-600",
      text: "text-fuchsia-700",
      border: "border-fuchsia-200",
      lightBg: "bg-fuchsia-50",
    },
  },
  {
    id: "shani",
    name: "शनि ग्रह",
    englishName: "Shani - Saturn",
    deity: "यम / प्रजापति",
    dhyanMantra: "नीलांजन समाभासं रविपुत्रं यमाग्रजम्।\nछायामार्तण्ड संभूतं तं नमामि शनैश्चरम्॥",
    gayatriMantra: "ॐ काकध्वजाय विद्महे खड्गहस्ताय धीमहि, तन्नो मन्दः प्रचोदयात्॥",
    vedoktaMantra: "ॐ शं नो देवीरभिष्टये आपो भवन्तु पीतये।\nशं योरभि स्रवन्तु नः ॥",
    beejMantra: "ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः ॥",
    japCount: "२३,००० (कलियुगे ९२,०००)",
    samidha: "शमी",
    gemstone: "नीलम (Blue Sapphire)",
    direction: "पश्चिम",
    colorTheme: {
      bg: "bg-blue-800",
      text: "text-blue-900",
      border: "border-blue-200",
      lightBg: "bg-blue-50",
    },
  },
  {
    id: "rahu",
    name: "राहु ग्रह",
    englishName: "Rahu - North Node",
    deity: "काल / सर्प",
    dhyanMantra: "अर्धकायं महावीर्यं चन्द्रादित्य विमर्दनम्।\nसिंहिकागर्भसंभूतं तं राहुं प्रणमाम्यहम्॥",
    gayatriMantra: "ॐ नागाधिराजाय विद्महे पद्महस्ताय धीमहि, तन्नो राहुः प्रचोदयात्॥",
    vedoktaMantra: "ॐ कयानश्चित्र आ भुवदूती सदावृधः सखा ।\nकया शचिष्ठया वृता ॥",
    beejMantra: "ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः ॥",
    japCount: "१८,००० (कलियुगे ७२,०००)",
    samidha: "दूर्वा",
    gemstone: "गोमेद (Hessonite)",
    direction: "नैऋत्य",
    colorTheme: {
      bg: "bg-stone-700",
      text: "text-stone-800",
      border: "border-stone-200",
      lightBg: "bg-stone-50",
    },
  },
  {
    id: "ketu",
    name: "केतु ग्रह",
    englishName: "Ketu - South Node",
    deity: "चित्रगुप्त / ब्रह्मा",
    dhyanMantra: "पलाशपुष्पसंकाशं तारकाग्रह मस्तकम्।\nरौद्रं रौद्रात्मकं घोरं तं केतुं प्रणमाम्यहम्॥",
    gayatriMantra: "ॐ अश्वाध्वजाय विद्महे शूलहस्ताय धीमहि, तन्नो केतुः प्रचोदयात्॥",
    vedoktaMantra: "ॐ केतुं कृण्वन्नकेतवे पेशो मर्या अपेशसे।\nसमुषद्भिरजायथाः ॥",
    beejMantra: "ॐ स्त्रां स्त्रीं स्त्रौं सः केतवे नमः ॥",
    japCount: "१७,००० (कलियुगे ६८,०००)",
    samidha: "कुशा",
    gemstone: "लहसुनिया (Cat's Eye)",
    direction: "नैऋत्य / वायव्य",
    colorTheme: {
      bg: "bg-slate-600",
      text: "text-slate-800",
      border: "border-slate-200",
      lightBg: "bg-slate-50",
    },
  },
];
