/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCitiesRouteImport } from './routes/api/cities'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiNearestCityRouteImport } from './routes/api/nearest-city'
import { Route as ApiPanchangaRouteImport } from './routes/api/panchanga'
import { Route as ApiPanchangaMonthRouteImport } from './routes/api/panchanga.month'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitiesRoute = ApiCitiesRouteImport.update({
  id: '/api/cities',
  path: '/api/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearestCityRoute = ApiNearestCityRouteImport.update({
  id: '/api/nearest-city',
  path: '/api/nearest-city',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanchangaRoute = ApiPanchangaRouteImport.update({
  id: '/api/panchanga',
  path: '/api/panchanga',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanchangaMonthRoute = ApiPanchangaMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => ApiPanchangaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cities': typeof ApiCitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/nearest-city': typeof ApiNearestCityRoute
  '/api/panchanga': typeof ApiPanchangaRouteWithChildren
  '/api/panchanga/month': typeof ApiPanchangaMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cities': typeof ApiCitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/nearest-city': typeof ApiNearestCityRoute
  '/api/panchanga': typeof ApiPanchangaRouteWithChildren
  '/api/panchanga/month': typeof ApiPanchangaMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cities': typeof ApiCitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/nearest-city': typeof ApiNearestCityRoute
  '/api/panchanga': typeof ApiPanchangaRouteWithChildren
  '/api/panchanga/month': typeof ApiPanchangaMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cities'
    | '/api/health'
    | '/api/nearest-city'
    | '/api/panchanga'
    | '/api/panchanga/month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cities'
    | '/api/health'
    | '/api/nearest-city'
    | '/api/panchanga'
    | '/api/panchanga/month'
  id:
    | '__root__'
    | '/'
    | '/api/cities'
    | '/api/health'
    | '/api/nearest-city'
    | '/api/panchanga'
    | '/api/panchanga/month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCitiesRoute: typeof ApiCitiesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNearestCityRoute: typeof ApiNearestCityRoute
  ApiPanchangaRoute: typeof ApiPanchangaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cities': {
      id: '/api/cities'
      path: '/api/cities'
      fullPath: '/api/cities'
      preLoaderRoute: typeof ApiCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearest-city': {
      id: '/api/nearest-city'
      path: '/api/nearest-city'
      fullPath: '/api/nearest-city'
      preLoaderRoute: typeof ApiNearestCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panchanga': {
      id: '/api/panchanga'
      path: '/api/panchanga'
      fullPath: '/api/panchanga'
      preLoaderRoute: typeof ApiPanchangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panchanga/month': {
      id: '/api/panchanga/month'
      path: '/month'
      fullPath: '/api/panchanga/month'
      preLoaderRoute: typeof ApiPanchangaMonthRouteImport
      parentRoute: typeof ApiPanchangaRoute
    }
  }
}

interface ApiPanchangaRouteChildren {
  ApiPanchangaMonthRoute: typeof ApiPanchangaMonthRoute
}

const ApiPanchangaRouteChildren: ApiPanchangaRouteChildren = {
  ApiPanchangaMonthRoute: ApiPanchangaMonthRoute,
}

const ApiPanchangaRouteWithChildren = ApiPanchangaRoute._addFileChildren(
  ApiPanchangaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCitiesRoute: ApiCitiesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNearestCityRoute: ApiNearestCityRoute,
  ApiPanchangaRoute: ApiPanchangaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
