/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCitiesRouteImport } from './routes/api/cities'
import { Route as ApiNearestCityRouteImport } from './routes/api/nearest-city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitiesRoute = ApiCitiesRouteImport.update({
  id: '/api/cities',
  path: '/api/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearestCityRoute = ApiNearestCityRouteImport.update({
  id: '/api/nearest-city',
  path: '/api/nearest-city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cities': typeof ApiCitiesRoute
  '/api/nearest-city': typeof ApiNearestCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cities': typeof ApiCitiesRoute
  '/api/nearest-city': typeof ApiNearestCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cities': typeof ApiCitiesRoute
  '/api/nearest-city': typeof ApiNearestCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cities' | '/api/nearest-city'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cities' | '/api/nearest-city'
  id: '__root__' | '/' | '/api/cities' | '/api/nearest-city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCitiesRoute: typeof ApiCitiesRoute
  ApiNearestCityRoute: typeof ApiNearestCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cities': {
      id: '/api/cities'
      path: '/api/cities'
      fullPath: '/api/cities'
      preLoaderRoute: typeof ApiCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearest-city': {
      id: '/api/nearest-city'
      path: '/api/nearest-city'
      fullPath: '/api/nearest-city'
      preLoaderRoute: typeof ApiNearestCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCitiesRoute: ApiCitiesRoute,
  ApiNearestCityRoute: ApiNearestCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
